### ISSUE TITLE
java 8 can't use

### ISSUE THREAD

**Issue by jayzch** [apache/maven-mvnd#547]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/mvndaemon/mvnd/client/DefaultClient has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by jayzch** [comment]
➜  mvnd git:(master) ✗ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Zulu 8.58.0.13-CA-macos-aarch64) (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Zulu 8.58.0.13-CA-macos-aarch64) (build 25.312-b07, mixed mode)

**Comment by lvchangqi** [comment]
Yes, The minimum runtime environment is jdk 11

**Comment by ppalaga** [comment]
I guess you are trying use mvnd on Apple M1 and because there is no native executable for that platform, you use the `mvnd.sh` script? 
Well, yes, the mvnd client module is the only one from the mvnd family that requires Java 11. For the Daemon and all its dependencies, Java 8 is enough. I further assume that you really want to run your build on Java 8 (because otherwise, you could just use Java 11 for both client and Daemon).

So to run your build on Java 8, you somehow need to reach that the client process uses Java 11+ and the Daemon uses Java 8.

An easy and dirty solution that comes to my mind would be to hardcode `JAVACMD` in `mvnd.sh` to your Java 11 `java` executable and make sure that `JAVA_HOME` env var points at Java 8.

Maybe @gnodet knows of a better solution?

**Comment by gnodet** [comment]
`mvnd` works on Apple M1 provided the rosetta layer is installed, see https://github.com/apache/maven-mvnd/issues/337#issuecomment-975603892
