### ISSUE TITLE
mvnd with lombok error

### ISSUE THREAD

**Issue by muyuanqiang7** [apache/maven-mvnd#550]
Spring Boot with lombok run `mvnd clean package` get error:
`java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x61094189) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module `
i found the problem is lombok version, i update the version of lombok solve the problem.

**Comment by muyuanqiang7** [comment]
update lombok version to latest

**Comment by lvchangqi** [comment]
it still has the same problem when i use jdk8 to compile my project

` Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x5b25551e) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x5b25551e`
