### ISSUE TITLE
Avoid caching parent with a version containing a property

### ISSUE THREAD

**Issue by Angie-Chiu** [apache/maven-mvnd#594]
I change the project version ，than run mvnd clean install ，but this console always show same version ，this version is before 
![image](https://user-images.githubusercontent.com/66293432/150988069-9d412af3-670b-483c-b5fd-135f1f9db242.png)

**Comment by ppalaga** [comment]
Does it work with `mvn` as expected? If not, it is not a `mvnd` specific issue.

I any case it would help if you were more specific what changes you do in which project (ideally provide a minimal reproducer project) and then describe clearly what you expect and what happens in reality.

**Comment by Angie-Chiu** [comment]
thank you ,run mvn is ok , I change the maven project's parent pom version , run mvnd clean install , project's  jar file version still before version ,  isn't new change project version

**Comment by ppalaga** [comment]
Thanks, in that case it would be nice if could please show a minimal reproducer project.

**Comment by calle2010** [comment]
I encountered a similar issue last week. See https://github.com/calle2010/mvdn-revision-issue for a minimal example with just a parent and a child pom.

Steps to reproduce:
1. `mvnd clean install` builds version 1 of parent and child
2. change property revision to 2 in parent POM
3. `mvnd clean install` builds version 2 of parent and version 1 child (wrong)

Reactor summary in this case is also different from mvn:

    [INFO] Reactor Summary:
    [INFO]
    [INFO] child 1 ............................................ SUCCESS [  0.676 s]
    [INFO] parent 2 ........................................... SUCCESS [  0.170 s]

4. `mvn clean install` builds version 2 of parent and child (correct)
5. `mvnd --stop; mvnd clean install` builds version 2 of parent and child (correct, but misses the point)

Since it works correctly after `mvnd --stop` it seems to me as if something is cached in the daemon.

Version information:

    mvnd native client 0.7.1-windows-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
    Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
    Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
    Maven home: C:\Apps\mvnd\mvn
    Java version: 11.0.14, vendor: Eclipse Adoptium, runtime: C:\Apps\jdk11
    Default locale: en_US, platform encoding: Cp1252
    OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by gnodet** [comment]
@calle2010 nice, that really helps to have a reproducible test, thx a ton !
