### ISSUE TITLE
runtime jdk requirement of java client (via mvnd.sh)  should be aligned to JDK8

### ISSUE THREAD

**Issue by gzm55** [apache/maven-mvnd#669]
Now java client (via `mvnd.sh`) requires JDK11, different with native `mvnd` and the embedded maven 3.8.5. This makes the user surprising in some production environments.

- Native `mvnd`: requires JDK8
- maven 3.8.5: requires JDK8
- `mvnd.sh`: requires JDK11 ?

**Comment by ppalaga** [comment]
> * Native `mvnd`: requires JDK8

Well, strictly speaking, `mvnd` is a native executable not requiring any JRE to run. A VM (called Substrate) is embedded. The daemon started by that executable is fine with Java 8.

> * maven 3.8.5: requires JDK8
> * `mvnd.sh`: requires JDK11 ?

Yes, this is by design. The client requires [some features](https://github.com/apache/maven-mvnd/issues/56) not available in Java 8. 

If you are on Mac M1 and you want to overcome this limitation, you may want to compile mvnd yourself following @orpiske 's script https://www.orpiske.net/2022/07/try-apache-maven-daemon/

We actually had a similar question before. Here is a dirty hack I recommended at that time: https://github.com/apache/maven-mvnd/issues/547#issuecomment-1004889625

**Comment by ppalaga** [comment]
Maybe we should document the limitation in README.

**Comment by gnodet** [comment]
I think this issue can now be closed with the merge of #717 and #722.
