### ISSUE TITLE
Timeout in client

### ISSUE THREAD

**Issue by gnodet** [apache/maven-mvnd#733]
The client sometimes assumes that the daemon has died because of the elapsed time between messages, while messages have been received after the last keep alive.
```
16:02:14.715 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-ses', message='[INFO] Generated components containing 1 Camel component: aws2-ses'}
16:02:14.715 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sns', message='[INFO] Changes detected - recompiling the module!'}
16:02:14.718 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sns', message='[INFO] Compiling 21 source files to /Users/gnodet/work/git/camel/components/camel-aws/camel-aws2-sns/target/classes'}
16:02:14.725 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-ses', message='[INFO] Validation complete'}
16:02:14.737 I Dispatch message: MojoStarted{artifactId='camel-aws2-ses', pluginGroupId='org.apache.maven.plugins', pluginArtifactId='maven-compiler-plugin', pluginVersion='3.10.1', mojo='compile', executionId='recompile'}
16:02:14.737 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-ses', message='[INFO] '}
16:02:14.737 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-ses', message='[INFO] --- maven-compiler-plugin:3.10.1:compile (recompile) @ camel-aws2-ses ---'}
16:02:14.838 I Dispatch message: KeepAlive
16:02:14.908 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-ses', message='[INFO] Changes detected - recompiling the module!'}
16:02:14.911 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-ses', message='[INFO] Compiling 13 source files to /Users/gnodet/work/git/camel/components/camel-aws/camel-aws2-ses/target/classes'}
16:02:15.012 I Dispatch message: KeepAlive
16:02:15.112 I Dispatch message: KeepAlive
16:02:15.212 I Dispatch message: KeepAlive
16:02:15.312 I Dispatch message: KeepAlive
16:02:15.413 I Dispatch message: KeepAlive
16:02:15.513 I Dispatch message: KeepAlive
16:02:15.614 I Dispatch message: KeepAlive
16:02:15.714 I Dispatch message: KeepAlive
16:02:15.814 I Dispatch message: KeepAlive
16:02:15.914 I Dispatch message: KeepAlive
16:02:16.015 I Dispatch message: KeepAlive
16:02:16.115 I Dispatch message: KeepAlive
16:02:16.216 I Dispatch message: KeepAlive
16:02:16.316 I Dispatch message: KeepAlive
16:02:16.416 I Dispatch message: KeepAlive
16:02:16.517 I Dispatch message: KeepAlive
16:02:16.617 I Dispatch message: KeepAlive
16:02:16.717 I Dispatch message: KeepAlive
16:02:16.819 I Dispatch message: KeepAlive
16:02:16.919 I Dispatch message: KeepAlive
16:02:17.020 I Dispatch message: KeepAlive
16:02:17.120 I Dispatch message: KeepAlive
16:02:17.132 D Expiration check running
16:02:17.221 I Dispatch message: KeepAlive
16:02:17.321 I Dispatch message: KeepAlive
16:02:17.422 I Dispatch message: KeepAlive
16:02:17.522 I Dispatch message: KeepAlive
16:02:17.623 I Dispatch message: KeepAlive
16:02:17.723 I Dispatch message: KeepAlive
16:02:17.823 I Dispatch message: KeepAlive
16:02:17.924 I Dispatch message: KeepAlive
16:02:18.024 I Dispatch message: KeepAlive
16:02:18.124 I Dispatch message: KeepAlive
16:02:18.225 I Dispatch message: KeepAlive
16:02:18.325 I Dispatch message: KeepAlive
16:02:18.426 I Dispatch message: KeepAlive
16:02:18.526 I Dispatch message: KeepAlive
16:02:18.626 I Dispatch message: KeepAlive
16:02:18.727 I Dispatch message: KeepAlive
16:02:18.827 I Dispatch message: KeepAlive
16:02:18.928 I Dispatch message: KeepAlive
16:02:19.028 I Dispatch message: KeepAlive
16:02:19.129 I Dispatch message: KeepAlive
16:02:19.230 I Dispatch message: KeepAlive
16:02:19.331 I Dispatch message: KeepAlive
16:02:19.431 I Dispatch message: KeepAlive
16:02:19.532 I Dispatch message: KeepAlive
16:02:19.632 I Dispatch message: KeepAlive
16:02:19.733 I Dispatch message: KeepAlive
16:02:19.833 I Dispatch message: KeepAlive
16:02:19.934 I Dispatch message: KeepAlive
16:02:20.034 I Dispatch message: KeepAlive
16:02:20.134 I Dispatch message: KeepAlive
16:02:20.234 I Dispatch message: KeepAlive
16:02:20.336 I Dispatch message: KeepAlive
16:02:20.436 I Dispatch message: KeepAlive
16:02:20.537 I Dispatch message: KeepAlive
16:02:20.637 I Dispatch message: KeepAlive
16:02:20.737 I Dispatch message: KeepAlive
16:02:20.838 I Dispatch message: KeepAlive
16:02:20.939 I Dispatch message: KeepAlive
16:02:21.040 I Dispatch message: KeepAlive
16:02:21.141 I Dispatch message: KeepAlive
16:02:21.241 I Dispatch message: KeepAlive
16:02:21.342 I Dispatch message: KeepAlive
16:02:21.442 I Dispatch message: KeepAlive
16:02:21.543 I Dispatch message: KeepAlive
16:02:21.644 I Dispatch message: KeepAlive
16:02:21.745 I Dispatch message: KeepAlive
16:02:21.846 I Dispatch message: KeepAlive
16:02:21.946 I Dispatch message: KeepAlive
16:02:25.058 I Dispatch message: KeepAlive
16:02:25.067 I Dispatch message: MojoStarted{artifactId='camel-aws2-sts', pluginGroupId='org.apache.maven.plugins', pluginArtifactId='maven-resources-plugin', pluginVersion='3.2.0', mojo='testResources', executionId='default-testResources'}
16:02:25.067 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] '}
16:02:25.067 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ camel-aws2-sts ---'}
16:02:25.072 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] Using 'UTF-8' encoding to copy filtered resources.'}
16:02:25.073 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] Using 'UTF-8' encoding to copy filtered properties files.'}
16:02:25.075 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] Copying 2 resources'}
16:02:25.083 I Dispatch message: MojoStarted{artifactId='camel-aws2-sts', pluginGroupId='org.apache.maven.plugins', pluginArtifactId='maven-compiler-plugin', pluginVersion='3.10.1', mojo='testCompile', executionId='default-testCompile'}
16:02:25.083 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] '}
16:02:25.083 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ camel-aws2-sts ---'}
16:02:25.091 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] Changes detected - recompiling the module!'}
16:02:25.092 I Dispatch message: ProjectLogMessage{projectId='camel-aws2-sts', message='[INFO] Compiling 11 source files to /Users/gnodet/work/git/camel/components/camel-aws/camel-aws2-sts/target/test-classes'}
16:02:25.192 I Dispatch message: KeepAlive
16:02:25.293 I Dispatch message: KeepAlive
16:02:25.393 I Dispatch message: KeepAlive
16:02:25.494 I Dispatch message: KeepAlive
----- End of the daemon log file -----
  output: /Users/gnodet/.m2/mvnd/registry/0.8.2/daemon-d723426a.out.log
----- Last  200 lines from daemon output - /Users/gnodet/.m2/mvnd/registry/0.8.2/daemon-d723426a.out.log -----
NOTE: Picked up JDK_JAVA_OPTIONS: --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED
----- End of the daemon output -----

	at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:129)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:334)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:144)
Caused by: java.io.IOException: No message received within 3000ms, daemon may have crashed. You may want to check its status using mvnd --status
	at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:111)
	... 2 more
```

**Comment by gnodet** [comment]
It may just be a coincidence that two keep alive messages have more than 3 seconds between them, but we need to investigate that it does not cause the failure.
```
16:02:21.946 I Dispatch message: KeepAlive
16:02:25.058 I Dispatch message: KeepAlive
```

**Comment by gnodet** [comment]
I don't really see how there could be a delay, so in my example, there must be another gap between the last message and the exception (on which there's no timestamp).

**Comment by ahmsay** [comment]
We have the same error in our project too. Fails in the Jenkins environment. It seems that the daemon really dies, that's why we get that error.

When running mvnd --status there is no daemon listed. Shouldn't they be idle?

**Comment by walnut-tom** [comment]
i'm too

Exception in thread "main" org.mvndaemon.mvnd.common.DaemonException$StaleAddressException: Could not receive a message from the daemon.
Daemon id: 95910015
  log file: /root/.m2/mvnd/registry/0.9.0/daemon-95910015.log
----- Last  200 lines from daemon log file - /root/.m2/mvnd/registry/0.9.0/daemon-95910015.log -----
14:01:40.296 I Dispatch message: KeepAlive
14:01:40.397 I Dispatch message: KeepAlive
14:01:40.497 I Dispatch message: KeepAlive
14:01:40.598 I Dispatch message: KeepAlive
14:01:40.789 I Dispatch message: KeepAlive
14:01:40.889 I Dispatch message: KeepAlive
14:01:40.990 I Dispatch message: KeepAlive
14:01:41.090 I Dispatch message: KeepAlive
14:01:41.191 I Dispatch message: KeepAlive
14:01:41.291 I Dispatch message: KeepAlive
14:01:41.392 I Dispatch message: KeepAlive
14:01:41.492 I Dispatch message: KeepAlive
14:01:41.592 I Dispatch message: KeepAlive
14:01:41.693 I Dispatch message: KeepAlive
14:01:41.793 I Dispatch message: KeepAlive
14:01:41.894 I Dispatch message: KeepAlive
14:01:41.994 I Dispatch message: KeepAlive
14:01:42.094 I Dispatch message: KeepAlive
14:01:42.195 I Dispatch message: KeepAlive
14:01:42.295 I Dispatch message: KeepAlive
14:01:42.396 I Dispatch message: KeepAlive
14:01:42.496 I Dispatch message: KeepAlive
14:01:42.597 I Dispatch message: KeepAlive
14:01:42.697 I Dispatch message: KeepAlive
14:01:42.834 I Dispatch message: KeepAlive
14:01:42.935 I Dispatch message: KeepAlive
14:01:43.035 I Dispatch message: KeepAlive
14:01:43.136 I Dispatch message: KeepAlive
14:01:43.236 I Dispatch message: KeepAlive
14:01:43.337 I Dispatch message: KeepAlive
14:01:43.437 I Dispatch message: KeepAlive
14:01:43.537 I Dispatch message: KeepAlive
14:01:43.638 I Dispatch message: KeepAlive
14:01:43.738 I Dispatch message: KeepAlive
14:01:43.839 I Dispatch message: KeepAlive
14:01:43.939 I Dispatch message: KeepAlive
14:01:44.039 I Dispatch message: KeepAlive
14:01:44.140 I Dispatch message: KeepAlive
14:01:44.240 I Dispatch message: KeepAlive
14:01:44.341 I Dispatch message: KeepAlive
14:01:44.441 I Dispatch message: KeepAlive
14:01:44.541 I Dispatch message: KeepAlive
14:01:44.642 I Dispatch message: KeepAlive
14:01:44.742 I Dispatch message: KeepAlive
14:01:44.843 I Dispatch message: KeepAlive
14:01:44.943 I Dispatch message: KeepAlive
14:01:45.043 I Dispatch message: KeepAlive
14:01:45.144 I Dispatch message: KeepAlive
14:01:45.244 I Dispatch message: KeepAlive
14:01:45.345 I Dispatch message: KeepAlive
14:01:45.445 I Dispatch message: KeepAlive
14:01:45.546 I Dispatch message: KeepAlive
14:01:45.646 I Dispatch message: KeepAlive
14:01:45.783 I Dispatch message: KeepAlive
14:01:45.884 I Dispatch message: KeepAlive
14:01:45.984 I Dispatch message: KeepAlive
14:01:46.084 I Dispatch message: KeepAlive
14:01:46.185 I Dispatch message: KeepAlive
14:01:46.285 I Dispatch message: KeepAlive
14:01:46.385 I Dispatch message: KeepAlive
14:01:46.486 I Dispatch message: KeepAlive
14:01:46.586 I Dispatch message: KeepAlive
14:01:46.687 I Dispatch message: KeepAlive
14:01:46.787 I Dispatch message: KeepAlive
14:01:46.887 I Dispatch message: KeepAlive
14:01:46.988 I Dispatch message: KeepAlive
14:01:47.088 I Dispatch message: KeepAlive
14:01:47.188 I Dispatch message: KeepAlive
14:01:47.289 I Dispatch message: KeepAlive
14:01:47.389 I Dispatch message: KeepAlive
14:01:47.490 I Dispatch message: KeepAlive
14:01:47.590 I Dispatch message: KeepAlive
14:01:47.691 I Dispatch message: KeepAlive
14:01:47.791 I Dispatch message: KeepAlive
14:01:47.892 I Dispatch message: KeepAlive
14:01:47.992 I Dispatch message: KeepAlive
14:01:48.017 D Expiration check running
14:01:48.224 I Dispatch message: KeepAlive
14:01:48.324 I Dispatch message: KeepAlive
14:01:48.424 I Dispatch message: KeepAlive
14:01:48.525 I Dispatch message: KeepAlive
14:01:48.625 I Dispatch message: KeepAlive
14:01:48.726 I Dispatch message: KeepAlive
14:01:48.826 I Dispatch message: KeepAlive
14:01:48.927 I Dispatch message: KeepAlive
14:01:49.027 I Dispatch message: KeepAlive
14:01:49.127 I Dispatch message: KeepAlive
14:01:49.228 I Dispatch message: KeepAlive
14:01:49.328 I Dispatch message: KeepAlive
14:01:49.428 I Dispatch message: KeepAlive
14:01:49.529 I Dispatch message: KeepAlive
14:01:49.630 I Dispatch message: KeepAlive
14:01:49.730 I Dispatch message: KeepAlive
14:01:49.831 I Dispatch message: KeepAlive
14:01:49.931 I Dispatch message: KeepAlive
14:01:50.032 I Dispatch message: KeepAlive
14:01:50.132 I Dispatch message: KeepAlive
14:01:50.278 I Dispatch message: KeepAlive
14:01:50.379 I Dispatch message: KeepAlive
14:01:50.479 I Dispatch message: KeepAlive
14:01:50.579 I Dispatch message: KeepAlive
14:01:50.680 I Dispatch message: KeepAlive
14:01:50.780 I Dispatch message: KeepAlive
14:01:50.881 I Dispatch message: KeepAlive
14:01:50.981 I Dispatch message: KeepAlive
14:01:51.082 I Dispatch message: KeepAlive
14:01:51.182 I Dispatch message: KeepAlive
14:01:51.283 I Dispatch message: KeepAlive
14:01:51.383 I Dispatch message: KeepAlive
14:01:51.483 I Dispatch message: KeepAlive
14:01:51.584 I Dispatch message: KeepAlive
14:01:51.684 I Dispatch message: KeepAlive
14:01:51.785 I Dispatch message: KeepAlive
14:01:51.885 I Dispatch message: KeepAlive
14:01:51.985 I Dispatch message: KeepAlive
14:01:52.086 I Dispatch message: KeepAlive
14:01:52.186 I Dispatch message: KeepAlive
14:01:52.617 I Dispatch message: KeepAlive
14:01:52.717 I Dispatch message: KeepAlive
14:01:52.818 I Dispatch message: KeepAlive
14:01:52.918 I Dispatch message: KeepAlive
14:01:53.018 I Dispatch message: KeepAlive
14:01:53.119 I Dispatch message: KeepAlive
14:01:53.219 I Dispatch message: KeepAlive
14:01:53.320 I Dispatch message: KeepAlive
14:01:53.420 I Dispatch message: KeepAlive
14:01:53.520 I Dispatch message: KeepAlive
14:01:53.621 I Dispatch message: KeepAlive
14:01:53.721 I Dispatch message: KeepAlive
14:01:53.822 I Dispatch message: KeepAlive
14:01:54.133 I Dispatch message: KeepAlive
14:01:54.234 I Dispatch message: KeepAlive
14:01:54.334 I Dispatch message: KeepAlive
14:01:54.435 I Dispatch message: KeepAlive
14:01:54.535 I Dispatch message: KeepAlive
14:01:54.636 I Dispatch message: KeepAlive
14:01:54.736 I Dispatch message: KeepAlive
14:01:54.837 I Dispatch message: KeepAlive
14:01:54.937 I Dispatch message: KeepAlive
14:01:55.038 I Dispatch message: KeepAlive
14:01:55.138 I Dispatch message: KeepAlive
14:01:55.238 I Dispatch message: KeepAlive
14:01:55.339 I Dispatch message: KeepAlive
14:01:55.439 I Dispatch message: KeepAlive
14:01:55.540 I Dispatch message: KeepAlive
14:01:55.837 I Dispatch message: KeepAlive
14:01:55.938 I Dispatch message: KeepAlive
14:01:56.038 I Dispatch message: KeepAlive
14:01:56.139 I Dispatch message: KeepAlive
14:01:56.239 I Dispatch message: KeepAlive
14:01:56.340 I Dispatch message: KeepAlive
14:01:56.440 I Dispatch message: KeepAlive
14:01:56.541 I Dispatch message: KeepAlive
14:01:56.641 I Dispatch message: KeepAlive
14:01:56.741 I Dispatch message: KeepAlive
14:01:56.842 I Dispatch message: KeepAlive
14:01:56.942 I Dispatch message: KeepAlive
14:01:57.043 I Dispatch message: KeepAlive
14:01:57.143 I Dispatch message: KeepAlive
14:01:57.386 I Dispatch message: KeepAlive
14:01:57.486 I Dispatch message: KeepAlive
14:01:57.586 I Dispatch message: KeepAlive
14:01:57.687 I Dispatch message: KeepAlive
14:01:57.787 I Dispatch message: KeepAlive
14:01:57.888 I Dispatch message: KeepAlive
14:01:57.988 I Dispatch message: KeepAlive
14:01:58.017 D Expiration check running
14:01:58.089 I Dispatch message: KeepAlive
14:01:58.189 I Dispatch message: KeepAlive
14:01:58.289 I Dispatch message: KeepAlive
14:01:58.390 I Dispatch message: KeepAlive
14:01:58.490 I Dispatch message: KeepAlive
14:01:58.591 I Dispatch message: KeepAlive
14:01:58.692 I Dispatch message: KeepAlive
14:01:58.792 I Dispatch message: KeepAlive
14:01:58.893 I Dispatch message: KeepAlive
14:01:58.993 I Dispatch message: KeepAlive
14:01:59.094 I Dispatch message: KeepAlive
14:01:59.194 I Dispatch message: KeepAlive
14:01:59.295 I Dispatch message: KeepAlive
14:01:59.395 I Dispatch message: KeepAlive
14:01:59.496 I Dispatch message: KeepAlive
14:01:59.596 I Dispatch message: KeepAlive
14:01:59.696 I Dispatch message: KeepAlive
14:01:59.797 I Dispatch message: KeepAlive
14:01:59.897 I Dispatch message: KeepAlive
14:01:59.997 I Dispatch message: KeepAlive
14:02:00.154 I Dispatch message: KeepAlive
14:02:00.255 I Dispatch message: KeepAlive
14:02:00.355 I Dispatch message: KeepAlive
14:02:00.456 I Dispatch message: KeepAlive
14:02:00.556 I Dispatch message: KeepAlive
14:02:00.656 I Dispatch message: KeepAlive
14:02:00.757 I Dispatch message: KeepAlive
14:02:00.857 I Dispatch message: KeepAlive
14:02:00.958 I Dispatch message: KeepAlive
14:02:01.058 I Dispatch message: KeepAlive
14:02:01.159 I Dispatch message: KeepAlive
14:02:01.259 I Dispatch message: KeepAlive
14:02:01.359 I Dispatch message: KeepAlive
----- End of the daemon log file -----
  output: /root/.m2/mvnd/registry/0.9.0/daemon-95910015.out.log
----- Last  200 lines from daemon output - /root/.m2/mvnd/registry/0.9.0/daemon-95910015.out.log -----
Starting daemon process: id = 95910015, workingDir = /opt/data/builder/workspace/dev/PFB73TTFDM/xxx, daemonArgs: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el9.x86_64/bin/java -classpath /usr/share/maven-mvnd-0.9.0-linux-amd64/lib/mvnd-common-0.9.0.jar:/usr/share/maven-mvnd-0.9.0-linux-amd64/lib/mvnd-agent-0.9.0.jar -javaagent:/usr/share/maven-mvnd-0.9.0-linux-amd64/lib/mvnd-agent-0.9.0.jar -Xmx2048m -Xms1024m -Djava.awt.headless=true -DtarLongFileMode=gnu -Dmvnd.home=/usr/share/maven-mvnd-0.9.0-linux-amd64 -Dmaven.home=/usr/share/maven-mvnd-0.9.0-linux-amd64 -Dmaven.conf=/usr/share/maven-mvnd-0.9.0-linux-amd64/conf -Dmvnd.java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.362.b08-3.el9.x86_64 -Dlogback.configurationFile=/usr/share/maven-mvnd-0.9.0-linux-amd64/conf/logging/logback-mvnd.xml -Dmvnd.id=95910015 -Dmvnd.daemonStorage=/root/.m2/mvnd/registry/0.9.0 -Dmvnd.registry=/root/.m2/mvnd/registry/0.9.0/registry.bin -Dmvnd.socketFamily=inet -Dmvnd.home=/usr/share/maven-mvnd-0.9.0-linux-amd64 -Djdk.java.options=--add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.jar=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Dmvnd.noDaemon=false -Dmvnd.debug=false -Dmvnd.debug.address=8000 -Dmvnd.idleTimeout=3h -Dmvnd.keepAlive=100ms -Dmvnd.extClasspath= -Dmvnd.coreExtensions= -Dmvnd.jvmArgs=-Xmx2048m -Xms1024m -Djava.awt.headless=true -DtarLongFileMode=gnu -Dmvnd.enableAssertions=false -Dmvnd.expirationCheckDelay=10s -Dmvnd.duplicateDaemonGracePeriod=10s -Dmvnd.socketFamily=inet org.mvndaemon.mvnd.common.MavenDaemon
----- End of the daemon output -----

	at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:138)
	at org.mvndaemon.mvnd.client.DefaultClient.execute(DefaultClient.java:353)
	at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:153)
Caused by: java.io.IOException: No message received within 3000ms, daemon may have crashed. You may want to check its status using mvnd --status
	at org.mvndaemon.mvnd.client.DaemonClientConnection.receive(DaemonClientConnection.java:119)
	... 2 more
