### ISSUE TITLE
After turning on debug, I hope there will be a hint

### ISSUE THREAD

**Issue by zhaoyunxing92** [apache/maven-mvnd#737]
I don't know if the startup is successful after I turn it on, and the port is not released after I disconnect it.

### Just like the following
``` shell
➜  todo git:(main) ✗ mvnDebug clean compile
Preparing to execute Maven in debug mode
Listening for transport dt_socket at address: 8000
```

**Comment by gnodet** [comment]
I agree a hint would be welcomed.  For the port, I also agree that given the port number is fixed, it would be preferable to release it.  The problem is that debug mode is turned on at for the JVM and I don't think there's a way to enable/disable remote debugging dynamically, which would mean the daemon would have to be killed.

**Comment by zhaoyunxing92** [comment]
Well, then manually kill
