### ISSUE TITLE
Make mvnd Java17

### ISSUE THREAD

**Issue by cstamas** [apache/maven-mvnd#954]
Fully. So both m39 and m40 should require Java17.
This is basically to simplify our own lives, and easier maintain. Maven4 is already Java17. 
If someone must have Java8 to build, should use Maven 3.9.x + smart builder.

**Comment by gnodet** [comment]
> Fully. So both m39 and m40 should require Java17. This is basically to simplify our own lives, and easier maintain. Maven4 is already Java17. If someone must have Java8 to build, should use Maven 3.9.x + smart builder.

That's not the hard part to maintain.  The hard part is the DaemonMavenCli.  If you really want to make a difference in term of maintenance, that's where things need to be fixed.
People did contribute a bunch of PRs to make mvnd work the very same way than maven does, so that they can be used interchangeably, I'm not really sure we want to loose that for no real benefit.
